version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm i -g yarn --unsafe-perm
      - npm i -g serverless@2.64.1 --unsafe-perm
  build:
    commands:
      - cd ./client/ && ./publish