#!/bin/bash

if [[ -e '.env.client' ]]
then
    . .env.client
fi

export REACT_APP_SITE_DOMAIN=$SITE_URL
export REACT_APP_API_URL=$API_URL

cd ./client/

yarn install
yarn run build-ssr

cd ../cdk/
yarn install
yarn run build
yarn cdk deploy