const ActionTypes = {
    GET_VIDEOS: 'GET_VIDEOS',
    GET_TAGGED_VIDEOS: 'GET_TAGGED_VIDEOS',
    RECEIVE_VIDEOS: 'RECEIVE_VIDEOS',
    GET_TAGS: 'GET_TAGS',
    GET_VIDEO_TAGS: 'GET_VIDEO_TAGS',
    ADD_TAGS: 'ADD_TAGS',
    REMOVE_TAGS: 'REMOVE_TAG',
    RECEIVE_TAGS: 'RECEIVE_TAGS'
}

export default ActionTypes;