const ActionTypes = {
    LOAD_SESSION: 'LOAD_SESSION',
    SET_SESSION: 'SET_SESSION',
    RECEIVE_VIDEOS: 'RECEIVE_VIDEOS',
    PUT_VIDEO: 'PUT_VIDEO',
    REMOVE_VIDEO: 'REMOVE_VIDEO',
    RECEIVE_DIRECTORIES: 'RECEIVE_DIRECTORIES',
    RECEIVE_TAGS: 'RECEIVE_TAGS'
}

export default ActionTypes;